### ISSUE TITLE
Should this be archived

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_conventions#1]
@giovannipizzi I didn't even know of the existence of this repo, but it seems like this is a very early predecessor to `aiida-common-workflows`. I take it we can archive (or even delete once we have taken out any useful information) this?

**Comment by giovannipizzi** [comment]
I agree! I had already archived it but then I could not reply :-D
I vote for deleting completely, this comes from the original discussions in a MaX hackathon in Barcelona IIRC, but I'd say it's all now in the common workflows (or it's old). I don't even think it's worth keeping for historical purposes.
@bosonie if OK also with you, then I'd delete this and have less confusion in the future

**Comment by bosonie** [comment]
I'm happy to have it removed!

**Comment by giovannipizzi** [comment]
I'm going to delete it, then (you might see this via email, or never ever see this :-D)
